
dist: trusty
sudo: required

language: bash

before_install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  # - sudo apt-get install iverilog -y
  - sudo apt-get install gperf -y
  - wget https://sourceforge.net/projects/iverilog/files/latest/download -O verilog.tar.gz
  - tar xvzf verilog.tar.gz
  - cd verilog*
  - ./configure && make
  - sudo make install
  - cd -
  - echo "#!/bin/bash" > /bin/notify-send; chmod +x /bin/notify-send

# install:
# before_script:

script:
  - make sim
